/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val a = 3
    val b = 2
    val c = 6
    if (a > 0) {
        println ("Funcion cuadratica:")
        println ("$a x² + $b x + $c")
        calcular(a,b,c)
    }
}
fun calcular(a:Int, b:Int, c:Int) {
    for (x in -5..5) {
        var y = a*(x*x)+b*x+c
        println ("Para x = $x , y vale $y")
    }
}